# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
 name: Stage the app

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'stage')
